SELECT 'Count of COURSE Table:' AS COUNTS, COUNT(*) AS ROW_COUNT
FROM course
GROUP BY 'Count of COURSE Table:'
UNION
SELECT 'Count of ENROLLMENT Table:', COUNT(*)
FROM enrollment
GROUP BY 'Count of ENROLLMENT Table:'
UNION
SELECT 'Count of GRADE Table:', COUNT(*)
FROM GRADE
GROUP BY 'Count of GRADE Table:'
UNION
SELECT 'Count of GRADE_CONVERSION Table:', COUNT(*)
FROM GRADE_CONVERSION
GROUP BY 'Count of GRADE_CONVERSION Table:'
UNION
SELECT 'Count of GRADE_TYPE Table:', COUNT(*)
FROM GRADE_TYPE
GROUP BY 'Count of GRADE_TYPE Table:'
UNION
SELECT 'Count of GRADE_TYPE_WEIGHT Table:', COUNT(*)
FROM GRADE_TYPE_WEIGHT
GROUP BY 'Count of GRADE_TYPE Table:'
UNION
SELECT 'Count of INSTRUCTOR Table:', COUNT(*)
FROM INSTRUCTOR
GROUP BY 'Count of INSTRUCTOR Table:'
UNION
SELECT 'Count of SECTION Table:', COUNT(*)
FROM SECTION
GROUP BY 'Count of SECTION Table:'
UNION
SELECT 'Count of SECTION Table:', COUNT(*)
FROM STUDENT
GROUP BY 'Count of SECTION Table:'
UNION
SELECT 'Count of SECTION Table:', COUNT(*)
FROM ZIPCODE
GROUP BY 'Count of ZIPCODE Table:';